Test:
    runs-on: ubuntu-latest
    needs: Train
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Pull Docker Image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/cicd_assignment:latest
 
    - name: Run Docker Image Check Score
      run: |
        # Run the docker image and evaluate if threshold is satisfied
        score=$(docker run ${{ secrets.DOCKER_USERNAME }}/cicd_assignment:latest)
        if (( $(echo "$score > 0.35" | bc -l) )); then
          echo "Score is greater than 0.35"
          exit 0
        else
          echo "Score is Not greater than 0.35"
          exit 1
        fi
